/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
	"time"
)

// VideoFull struct for VideoFull
type VideoFull struct {
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Type *string `json:"type,omitempty"`
	// corresponds to a Topic ID, Videos of type `clip` cannot not have topic. Streams may or may not have topic.
	TopicId NullableString `json:"topic_id,omitempty"`
	PublishedAt NullableTime `json:"published_at,omitempty"`
	// Takes on the first non-null value of end_actual, start_actual, start_scheduled, or published_at
	AvailableAt *time.Time `json:"available_at,omitempty"`
	// Duration of the video in seconds
	Duration *int32 `json:"duration,omitempty"`
	Status *string `json:"status,omitempty"`
	// Included when includes contains 'live_info'
	StartScheduled NullableTime `json:"start_scheduled,omitempty"`
	// Included when includes contains 'live_info'
	StartActual NullableTime `json:"start_actual,omitempty"`
	// Included when includes contains 'live_info'
	EndActual NullableTime `json:"end_actual,omitempty"`
	// Included when includes contains 'live_info'
	LiveViewers NullableInt32 `json:"live_viewers,omitempty"`
	// Included when includes contains 'description'
	Description *string `json:"description,omitempty"`
	// Number of tagged songs for this video
	Songcount *float32 `json:"songcount,omitempty"`
	ChannelId *string `json:"channel_id,omitempty"`
	// Included when 'includes' contains 'clips'
	Clips []VideoWithChannel `json:"clips,omitempty"`
	// Included when 'includes' contains 'sources'
	Sources []VideoWithChannel `json:"sources,omitempty"`
	// Included when 'includes' contains 'refers'
	Refers []VideoWithChannel `json:"refers,omitempty"`
	// Included when 'includes' contains 'simulcasts'
	Simulcasts []VideoWithChannel `json:"simulcasts,omitempty"`
	// VTubers mentioned by this video, Included when 'includes' contains 'mentions'
	Mentions []ChannelMin `json:"mentions,omitempty"`
	// Number of songs
	Songs NullableFloat32 `json:"songs,omitempty"`
}

// NewVideoFull instantiates a new VideoFull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoFull() *VideoFull {
	this := VideoFull{}
	return &this
}

// NewVideoFullWithDefaults instantiates a new VideoFull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoFullWithDefaults() *VideoFull {
	this := VideoFull{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VideoFull) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VideoFull) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VideoFull) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *VideoFull) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *VideoFull) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *VideoFull) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *VideoFull) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *VideoFull) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *VideoFull) SetType(v string) {
	o.Type = &v
}

// GetTopicId returns the TopicId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetTopicId() string {
	if o == nil || o.TopicId.Get() == nil {
		var ret string
		return ret
	}
	return *o.TopicId.Get()
}

// GetTopicIdOk returns a tuple with the TopicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetTopicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopicId.Get(), o.TopicId.IsSet()
}

// HasTopicId returns a boolean if a field has been set.
func (o *VideoFull) HasTopicId() bool {
	if o != nil && o.TopicId.IsSet() {
		return true
	}

	return false
}

// SetTopicId gets a reference to the given NullableString and assigns it to the TopicId field.
func (o *VideoFull) SetTopicId(v string) {
	o.TopicId.Set(&v)
}
// SetTopicIdNil sets the value for TopicId to be an explicit nil
func (o *VideoFull) SetTopicIdNil() {
	o.TopicId.Set(nil)
}

// UnsetTopicId ensures that no value is present for TopicId, not even an explicit nil
func (o *VideoFull) UnsetTopicId() {
	o.TopicId.Unset()
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetPublishedAt() time.Time {
	if o == nil || o.PublishedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt.Get()
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedAt.Get(), o.PublishedAt.IsSet()
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *VideoFull) HasPublishedAt() bool {
	if o != nil && o.PublishedAt.IsSet() {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given NullableTime and assigns it to the PublishedAt field.
func (o *VideoFull) SetPublishedAt(v time.Time) {
	o.PublishedAt.Set(&v)
}
// SetPublishedAtNil sets the value for PublishedAt to be an explicit nil
func (o *VideoFull) SetPublishedAtNil() {
	o.PublishedAt.Set(nil)
}

// UnsetPublishedAt ensures that no value is present for PublishedAt, not even an explicit nil
func (o *VideoFull) UnsetPublishedAt() {
	o.PublishedAt.Unset()
}

// GetAvailableAt returns the AvailableAt field value if set, zero value otherwise.
func (o *VideoFull) GetAvailableAt() time.Time {
	if o == nil || o.AvailableAt == nil {
		var ret time.Time
		return ret
	}
	return *o.AvailableAt
}

// GetAvailableAtOk returns a tuple with the AvailableAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetAvailableAtOk() (*time.Time, bool) {
	if o == nil || o.AvailableAt == nil {
		return nil, false
	}
	return o.AvailableAt, true
}

// HasAvailableAt returns a boolean if a field has been set.
func (o *VideoFull) HasAvailableAt() bool {
	if o != nil && o.AvailableAt != nil {
		return true
	}

	return false
}

// SetAvailableAt gets a reference to the given time.Time and assigns it to the AvailableAt field.
func (o *VideoFull) SetAvailableAt(v time.Time) {
	o.AvailableAt = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *VideoFull) GetDuration() int32 {
	if o == nil || o.Duration == nil {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetDurationOk() (*int32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *VideoFull) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *VideoFull) SetDuration(v int32) {
	o.Duration = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VideoFull) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VideoFull) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *VideoFull) SetStatus(v string) {
	o.Status = &v
}

// GetStartScheduled returns the StartScheduled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetStartScheduled() time.Time {
	if o == nil || o.StartScheduled.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartScheduled.Get()
}

// GetStartScheduledOk returns a tuple with the StartScheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetStartScheduledOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartScheduled.Get(), o.StartScheduled.IsSet()
}

// HasStartScheduled returns a boolean if a field has been set.
func (o *VideoFull) HasStartScheduled() bool {
	if o != nil && o.StartScheduled.IsSet() {
		return true
	}

	return false
}

// SetStartScheduled gets a reference to the given NullableTime and assigns it to the StartScheduled field.
func (o *VideoFull) SetStartScheduled(v time.Time) {
	o.StartScheduled.Set(&v)
}
// SetStartScheduledNil sets the value for StartScheduled to be an explicit nil
func (o *VideoFull) SetStartScheduledNil() {
	o.StartScheduled.Set(nil)
}

// UnsetStartScheduled ensures that no value is present for StartScheduled, not even an explicit nil
func (o *VideoFull) UnsetStartScheduled() {
	o.StartScheduled.Unset()
}

// GetStartActual returns the StartActual field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetStartActual() time.Time {
	if o == nil || o.StartActual.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartActual.Get()
}

// GetStartActualOk returns a tuple with the StartActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetStartActualOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartActual.Get(), o.StartActual.IsSet()
}

// HasStartActual returns a boolean if a field has been set.
func (o *VideoFull) HasStartActual() bool {
	if o != nil && o.StartActual.IsSet() {
		return true
	}

	return false
}

// SetStartActual gets a reference to the given NullableTime and assigns it to the StartActual field.
func (o *VideoFull) SetStartActual(v time.Time) {
	o.StartActual.Set(&v)
}
// SetStartActualNil sets the value for StartActual to be an explicit nil
func (o *VideoFull) SetStartActualNil() {
	o.StartActual.Set(nil)
}

// UnsetStartActual ensures that no value is present for StartActual, not even an explicit nil
func (o *VideoFull) UnsetStartActual() {
	o.StartActual.Unset()
}

// GetEndActual returns the EndActual field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetEndActual() time.Time {
	if o == nil || o.EndActual.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.EndActual.Get()
}

// GetEndActualOk returns a tuple with the EndActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetEndActualOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndActual.Get(), o.EndActual.IsSet()
}

// HasEndActual returns a boolean if a field has been set.
func (o *VideoFull) HasEndActual() bool {
	if o != nil && o.EndActual.IsSet() {
		return true
	}

	return false
}

// SetEndActual gets a reference to the given NullableTime and assigns it to the EndActual field.
func (o *VideoFull) SetEndActual(v time.Time) {
	o.EndActual.Set(&v)
}
// SetEndActualNil sets the value for EndActual to be an explicit nil
func (o *VideoFull) SetEndActualNil() {
	o.EndActual.Set(nil)
}

// UnsetEndActual ensures that no value is present for EndActual, not even an explicit nil
func (o *VideoFull) UnsetEndActual() {
	o.EndActual.Unset()
}

// GetLiveViewers returns the LiveViewers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetLiveViewers() int32 {
	if o == nil || o.LiveViewers.Get() == nil {
		var ret int32
		return ret
	}
	return *o.LiveViewers.Get()
}

// GetLiveViewersOk returns a tuple with the LiveViewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetLiveViewersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LiveViewers.Get(), o.LiveViewers.IsSet()
}

// HasLiveViewers returns a boolean if a field has been set.
func (o *VideoFull) HasLiveViewers() bool {
	if o != nil && o.LiveViewers.IsSet() {
		return true
	}

	return false
}

// SetLiveViewers gets a reference to the given NullableInt32 and assigns it to the LiveViewers field.
func (o *VideoFull) SetLiveViewers(v int32) {
	o.LiveViewers.Set(&v)
}
// SetLiveViewersNil sets the value for LiveViewers to be an explicit nil
func (o *VideoFull) SetLiveViewersNil() {
	o.LiveViewers.Set(nil)
}

// UnsetLiveViewers ensures that no value is present for LiveViewers, not even an explicit nil
func (o *VideoFull) UnsetLiveViewers() {
	o.LiveViewers.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VideoFull) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VideoFull) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VideoFull) SetDescription(v string) {
	o.Description = &v
}

// GetSongcount returns the Songcount field value if set, zero value otherwise.
func (o *VideoFull) GetSongcount() float32 {
	if o == nil || o.Songcount == nil {
		var ret float32
		return ret
	}
	return *o.Songcount
}

// GetSongcountOk returns a tuple with the Songcount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetSongcountOk() (*float32, bool) {
	if o == nil || o.Songcount == nil {
		return nil, false
	}
	return o.Songcount, true
}

// HasSongcount returns a boolean if a field has been set.
func (o *VideoFull) HasSongcount() bool {
	if o != nil && o.Songcount != nil {
		return true
	}

	return false
}

// SetSongcount gets a reference to the given float32 and assigns it to the Songcount field.
func (o *VideoFull) SetSongcount(v float32) {
	o.Songcount = &v
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *VideoFull) GetChannelId() string {
	if o == nil || o.ChannelId == nil {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoFull) GetChannelIdOk() (*string, bool) {
	if o == nil || o.ChannelId == nil {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *VideoFull) HasChannelId() bool {
	if o != nil && o.ChannelId != nil {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *VideoFull) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetClips returns the Clips field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetClips() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Clips
}

// GetClipsOk returns a tuple with the Clips field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetClipsOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Clips == nil {
		return nil, false
	}
	return o.Clips, true
}

// HasClips returns a boolean if a field has been set.
func (o *VideoFull) HasClips() bool {
	if o != nil && o.Clips != nil {
		return true
	}

	return false
}

// SetClips gets a reference to the given []VideoWithChannel and assigns it to the Clips field.
func (o *VideoFull) SetClips(v []VideoWithChannel) {
	o.Clips = v
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetSources() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetSourcesOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *VideoFull) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []VideoWithChannel and assigns it to the Sources field.
func (o *VideoFull) SetSources(v []VideoWithChannel) {
	o.Sources = v
}

// GetRefers returns the Refers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetRefers() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Refers
}

// GetRefersOk returns a tuple with the Refers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetRefersOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Refers == nil {
		return nil, false
	}
	return o.Refers, true
}

// HasRefers returns a boolean if a field has been set.
func (o *VideoFull) HasRefers() bool {
	if o != nil && o.Refers != nil {
		return true
	}

	return false
}

// SetRefers gets a reference to the given []VideoWithChannel and assigns it to the Refers field.
func (o *VideoFull) SetRefers(v []VideoWithChannel) {
	o.Refers = v
}

// GetSimulcasts returns the Simulcasts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetSimulcasts() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Simulcasts
}

// GetSimulcastsOk returns a tuple with the Simulcasts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetSimulcastsOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Simulcasts == nil {
		return nil, false
	}
	return o.Simulcasts, true
}

// HasSimulcasts returns a boolean if a field has been set.
func (o *VideoFull) HasSimulcasts() bool {
	if o != nil && o.Simulcasts != nil {
		return true
	}

	return false
}

// SetSimulcasts gets a reference to the given []VideoWithChannel and assigns it to the Simulcasts field.
func (o *VideoFull) SetSimulcasts(v []VideoWithChannel) {
	o.Simulcasts = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetMentions() []ChannelMin {
	if o == nil {
		var ret []ChannelMin
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetMentionsOk() ([]ChannelMin, bool) {
	if o == nil || o.Mentions == nil {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *VideoFull) HasMentions() bool {
	if o != nil && o.Mentions != nil {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []ChannelMin and assigns it to the Mentions field.
func (o *VideoFull) SetMentions(v []ChannelMin) {
	o.Mentions = v
}

// GetSongs returns the Songs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoFull) GetSongs() float32 {
	if o == nil || o.Songs.Get() == nil {
		var ret float32
		return ret
	}
	return *o.Songs.Get()
}

// GetSongsOk returns a tuple with the Songs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoFull) GetSongsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Songs.Get(), o.Songs.IsSet()
}

// HasSongs returns a boolean if a field has been set.
func (o *VideoFull) HasSongs() bool {
	if o != nil && o.Songs.IsSet() {
		return true
	}

	return false
}

// SetSongs gets a reference to the given NullableFloat32 and assigns it to the Songs field.
func (o *VideoFull) SetSongs(v float32) {
	o.Songs.Set(&v)
}
// SetSongsNil sets the value for Songs to be an explicit nil
func (o *VideoFull) SetSongsNil() {
	o.Songs.Set(nil)
}

// UnsetSongs ensures that no value is present for Songs, not even an explicit nil
func (o *VideoFull) UnsetSongs() {
	o.Songs.Unset()
}

func (o VideoFull) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.TopicId.IsSet() {
		toSerialize["topic_id"] = o.TopicId.Get()
	}
	if o.PublishedAt.IsSet() {
		toSerialize["published_at"] = o.PublishedAt.Get()
	}
	if o.AvailableAt != nil {
		toSerialize["available_at"] = o.AvailableAt
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StartScheduled.IsSet() {
		toSerialize["start_scheduled"] = o.StartScheduled.Get()
	}
	if o.StartActual.IsSet() {
		toSerialize["start_actual"] = o.StartActual.Get()
	}
	if o.EndActual.IsSet() {
		toSerialize["end_actual"] = o.EndActual.Get()
	}
	if o.LiveViewers.IsSet() {
		toSerialize["live_viewers"] = o.LiveViewers.Get()
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Songcount != nil {
		toSerialize["songcount"] = o.Songcount
	}
	if o.ChannelId != nil {
		toSerialize["channel_id"] = o.ChannelId
	}
	if o.Clips != nil {
		toSerialize["clips"] = o.Clips
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	if o.Refers != nil {
		toSerialize["refers"] = o.Refers
	}
	if o.Simulcasts != nil {
		toSerialize["simulcasts"] = o.Simulcasts
	}
	if o.Mentions != nil {
		toSerialize["mentions"] = o.Mentions
	}
	if o.Songs.IsSet() {
		toSerialize["songs"] = o.Songs.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableVideoFull struct {
	value *VideoFull
	isSet bool
}

func (v NullableVideoFull) Get() *VideoFull {
	return v.value
}

func (v *NullableVideoFull) Set(val *VideoFull) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoFull) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoFull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoFull(val *VideoFull) *NullableVideoFull {
	return &NullableVideoFull{value: val, isSet: true}
}

func (v NullableVideoFull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoFull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


