/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
)

// PostSearchCommentSearch200ResponseOneOf struct for PostSearchCommentSearch200ResponseOneOf
type PostSearchCommentSearch200ResponseOneOf struct {
	Total *float32 `json:"total,omitempty"`
	Items []PostSearchCommentSearch200ResponseOneOfInner `json:"items,omitempty"`
}

// NewPostSearchCommentSearch200ResponseOneOf instantiates a new PostSearchCommentSearch200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostSearchCommentSearch200ResponseOneOf() *PostSearchCommentSearch200ResponseOneOf {
	this := PostSearchCommentSearch200ResponseOneOf{}
	return &this
}

// NewPostSearchCommentSearch200ResponseOneOfWithDefaults instantiates a new PostSearchCommentSearch200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostSearchCommentSearch200ResponseOneOfWithDefaults() *PostSearchCommentSearch200ResponseOneOf {
	this := PostSearchCommentSearch200ResponseOneOf{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PostSearchCommentSearch200ResponseOneOf) GetTotal() float32 {
	if o == nil || o.Total == nil {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchCommentSearch200ResponseOneOf) GetTotalOk() (*float32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PostSearchCommentSearch200ResponseOneOf) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *PostSearchCommentSearch200ResponseOneOf) SetTotal(v float32) {
	o.Total = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PostSearchCommentSearch200ResponseOneOf) GetItems() []PostSearchCommentSearch200ResponseOneOfInner {
	if o == nil || o.Items == nil {
		var ret []PostSearchCommentSearch200ResponseOneOfInner
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchCommentSearch200ResponseOneOf) GetItemsOk() ([]PostSearchCommentSearch200ResponseOneOfInner, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PostSearchCommentSearch200ResponseOneOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PostSearchCommentSearch200ResponseOneOfInner and assigns it to the Items field.
func (o *PostSearchCommentSearch200ResponseOneOf) SetItems(v []PostSearchCommentSearch200ResponseOneOfInner) {
	o.Items = v
}

func (o PostSearchCommentSearch200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullablePostSearchCommentSearch200ResponseOneOf struct {
	value *PostSearchCommentSearch200ResponseOneOf
	isSet bool
}

func (v NullablePostSearchCommentSearch200ResponseOneOf) Get() *PostSearchCommentSearch200ResponseOneOf {
	return v.value
}

func (v *NullablePostSearchCommentSearch200ResponseOneOf) Set(val *PostSearchCommentSearch200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePostSearchCommentSearch200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePostSearchCommentSearch200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostSearchCommentSearch200ResponseOneOf(val *PostSearchCommentSearch200ResponseOneOf) *NullablePostSearchCommentSearch200ResponseOneOf {
	return &NullablePostSearchCommentSearch200ResponseOneOf{value: val, isSet: true}
}

func (v NullablePostSearchCommentSearch200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostSearchCommentSearch200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


