/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
)

// PostSearchCommentSearch200ResponseOneOfInnerAllOf struct for PostSearchCommentSearch200ResponseOneOfInnerAllOf
type PostSearchCommentSearch200ResponseOneOfInnerAllOf struct {
	Comments []Comment `json:"comments,omitempty"`
}

// NewPostSearchCommentSearch200ResponseOneOfInnerAllOf instantiates a new PostSearchCommentSearch200ResponseOneOfInnerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostSearchCommentSearch200ResponseOneOfInnerAllOf() *PostSearchCommentSearch200ResponseOneOfInnerAllOf {
	this := PostSearchCommentSearch200ResponseOneOfInnerAllOf{}
	return &this
}

// NewPostSearchCommentSearch200ResponseOneOfInnerAllOfWithDefaults instantiates a new PostSearchCommentSearch200ResponseOneOfInnerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostSearchCommentSearch200ResponseOneOfInnerAllOfWithDefaults() *PostSearchCommentSearch200ResponseOneOfInnerAllOf {
	this := PostSearchCommentSearch200ResponseOneOfInnerAllOf{}
	return &this
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PostSearchCommentSearch200ResponseOneOfInnerAllOf) GetComments() []Comment {
	if o == nil || o.Comments == nil {
		var ret []Comment
		return ret
	}
	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchCommentSearch200ResponseOneOfInnerAllOf) GetCommentsOk() ([]Comment, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PostSearchCommentSearch200ResponseOneOfInnerAllOf) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given []Comment and assigns it to the Comments field.
func (o *PostSearchCommentSearch200ResponseOneOfInnerAllOf) SetComments(v []Comment) {
	o.Comments = v
}

func (o PostSearchCommentSearch200ResponseOneOfInnerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	return json.Marshal(toSerialize)
}

type NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf struct {
	value *PostSearchCommentSearch200ResponseOneOfInnerAllOf
	isSet bool
}

func (v NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) Get() *PostSearchCommentSearch200ResponseOneOfInnerAllOf {
	return v.value
}

func (v *NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) Set(val *PostSearchCommentSearch200ResponseOneOfInnerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostSearchCommentSearch200ResponseOneOfInnerAllOf(val *PostSearchCommentSearch200ResponseOneOfInnerAllOf) *NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf {
	return &NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf{value: val, isSet: true}
}

func (v NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostSearchCommentSearch200ResponseOneOfInnerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


