/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
)

// PostSearchVideoSearch200ResponseOneOf struct for PostSearchVideoSearch200ResponseOneOf
type PostSearchVideoSearch200ResponseOneOf struct {
	Total *float32 `json:"total,omitempty"`
	Items []VideoWithChannel `json:"items,omitempty"`
}

// NewPostSearchVideoSearch200ResponseOneOf instantiates a new PostSearchVideoSearch200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostSearchVideoSearch200ResponseOneOf() *PostSearchVideoSearch200ResponseOneOf {
	this := PostSearchVideoSearch200ResponseOneOf{}
	return &this
}

// NewPostSearchVideoSearch200ResponseOneOfWithDefaults instantiates a new PostSearchVideoSearch200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostSearchVideoSearch200ResponseOneOfWithDefaults() *PostSearchVideoSearch200ResponseOneOf {
	this := PostSearchVideoSearch200ResponseOneOf{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PostSearchVideoSearch200ResponseOneOf) GetTotal() float32 {
	if o == nil || o.Total == nil {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchVideoSearch200ResponseOneOf) GetTotalOk() (*float32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PostSearchVideoSearch200ResponseOneOf) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *PostSearchVideoSearch200ResponseOneOf) SetTotal(v float32) {
	o.Total = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PostSearchVideoSearch200ResponseOneOf) GetItems() []VideoWithChannel {
	if o == nil || o.Items == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchVideoSearch200ResponseOneOf) GetItemsOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PostSearchVideoSearch200ResponseOneOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []VideoWithChannel and assigns it to the Items field.
func (o *PostSearchVideoSearch200ResponseOneOf) SetItems(v []VideoWithChannel) {
	o.Items = v
}

func (o PostSearchVideoSearch200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullablePostSearchVideoSearch200ResponseOneOf struct {
	value *PostSearchVideoSearch200ResponseOneOf
	isSet bool
}

func (v NullablePostSearchVideoSearch200ResponseOneOf) Get() *PostSearchVideoSearch200ResponseOneOf {
	return v.value
}

func (v *NullablePostSearchVideoSearch200ResponseOneOf) Set(val *PostSearchVideoSearch200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePostSearchVideoSearch200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePostSearchVideoSearch200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostSearchVideoSearch200ResponseOneOf(val *PostSearchVideoSearch200ResponseOneOf) *NullablePostSearchVideoSearch200ResponseOneOf {
	return &NullablePostSearchVideoSearch200ResponseOneOf{value: val, isSet: true}
}

func (v NullablePostSearchVideoSearch200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostSearchVideoSearch200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


