/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
	"time"
)

// GetVideosVideoId200Response struct for GetVideosVideoId200Response
type GetVideosVideoId200Response struct {
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Type *string `json:"type,omitempty"`
	// corresponds to a Topic ID, Videos of type `clip` cannot not have topic. Streams may or may not have topic.
	TopicId NullableString `json:"topic_id,omitempty"`
	PublishedAt NullableTime `json:"published_at,omitempty"`
	// Takes on the first non-null value of end_actual, start_actual, start_scheduled, or published_at
	AvailableAt *time.Time `json:"available_at,omitempty"`
	// Duration of the video in seconds
	Duration *int32 `json:"duration,omitempty"`
	Status *string `json:"status,omitempty"`
	// Included when includes contains 'live_info'
	StartScheduled NullableTime `json:"start_scheduled,omitempty"`
	// Included when includes contains 'live_info'
	StartActual NullableTime `json:"start_actual,omitempty"`
	// Included when includes contains 'live_info'
	EndActual NullableTime `json:"end_actual,omitempty"`
	// Included when includes contains 'live_info'
	LiveViewers NullableInt32 `json:"live_viewers,omitempty"`
	// Included when includes contains 'description'
	Description *string `json:"description,omitempty"`
	// Number of tagged songs for this video
	Songcount *float32 `json:"songcount,omitempty"`
	ChannelId *string `json:"channel_id,omitempty"`
	// Included when 'includes' contains 'clips'
	Clips []VideoWithChannel `json:"clips,omitempty"`
	// Included when 'includes' contains 'sources'
	Sources []VideoWithChannel `json:"sources,omitempty"`
	// Included when 'includes' contains 'refers'
	Refers []VideoWithChannel `json:"refers,omitempty"`
	// Included when 'includes' contains 'simulcasts'
	Simulcasts []VideoWithChannel `json:"simulcasts,omitempty"`
	// VTubers mentioned by this video, Included when 'includes' contains 'mentions'
	Mentions []ChannelMin `json:"mentions,omitempty"`
	// Number of songs
	Songs NullableFloat32 `json:"songs,omitempty"`
	// Comments are only returned if c === '1'
	Comments []Comment `json:"comments,omitempty"`
	Recommendations []Video `json:"recommendations,omitempty"`
}

// NewGetVideosVideoId200Response instantiates a new GetVideosVideoId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideosVideoId200Response() *GetVideosVideoId200Response {
	this := GetVideosVideoId200Response{}
	return &this
}

// NewGetVideosVideoId200ResponseWithDefaults instantiates a new GetVideosVideoId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideosVideoId200ResponseWithDefaults() *GetVideosVideoId200Response {
	this := GetVideosVideoId200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetVideosVideoId200Response) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetVideosVideoId200Response) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetVideosVideoId200Response) SetType(v string) {
	o.Type = &v
}

// GetTopicId returns the TopicId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetTopicId() string {
	if o == nil || o.TopicId.Get() == nil {
		var ret string
		return ret
	}
	return *o.TopicId.Get()
}

// GetTopicIdOk returns a tuple with the TopicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetTopicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopicId.Get(), o.TopicId.IsSet()
}

// HasTopicId returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasTopicId() bool {
	if o != nil && o.TopicId.IsSet() {
		return true
	}

	return false
}

// SetTopicId gets a reference to the given NullableString and assigns it to the TopicId field.
func (o *GetVideosVideoId200Response) SetTopicId(v string) {
	o.TopicId.Set(&v)
}
// SetTopicIdNil sets the value for TopicId to be an explicit nil
func (o *GetVideosVideoId200Response) SetTopicIdNil() {
	o.TopicId.Set(nil)
}

// UnsetTopicId ensures that no value is present for TopicId, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetTopicId() {
	o.TopicId.Unset()
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetPublishedAt() time.Time {
	if o == nil || o.PublishedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt.Get()
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedAt.Get(), o.PublishedAt.IsSet()
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasPublishedAt() bool {
	if o != nil && o.PublishedAt.IsSet() {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given NullableTime and assigns it to the PublishedAt field.
func (o *GetVideosVideoId200Response) SetPublishedAt(v time.Time) {
	o.PublishedAt.Set(&v)
}
// SetPublishedAtNil sets the value for PublishedAt to be an explicit nil
func (o *GetVideosVideoId200Response) SetPublishedAtNil() {
	o.PublishedAt.Set(nil)
}

// UnsetPublishedAt ensures that no value is present for PublishedAt, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetPublishedAt() {
	o.PublishedAt.Unset()
}

// GetAvailableAt returns the AvailableAt field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetAvailableAt() time.Time {
	if o == nil || o.AvailableAt == nil {
		var ret time.Time
		return ret
	}
	return *o.AvailableAt
}

// GetAvailableAtOk returns a tuple with the AvailableAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetAvailableAtOk() (*time.Time, bool) {
	if o == nil || o.AvailableAt == nil {
		return nil, false
	}
	return o.AvailableAt, true
}

// HasAvailableAt returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasAvailableAt() bool {
	if o != nil && o.AvailableAt != nil {
		return true
	}

	return false
}

// SetAvailableAt gets a reference to the given time.Time and assigns it to the AvailableAt field.
func (o *GetVideosVideoId200Response) SetAvailableAt(v time.Time) {
	o.AvailableAt = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetDuration() int32 {
	if o == nil || o.Duration == nil {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetDurationOk() (*int32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *GetVideosVideoId200Response) SetDuration(v int32) {
	o.Duration = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVideosVideoId200Response) SetStatus(v string) {
	o.Status = &v
}

// GetStartScheduled returns the StartScheduled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetStartScheduled() time.Time {
	if o == nil || o.StartScheduled.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartScheduled.Get()
}

// GetStartScheduledOk returns a tuple with the StartScheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetStartScheduledOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartScheduled.Get(), o.StartScheduled.IsSet()
}

// HasStartScheduled returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasStartScheduled() bool {
	if o != nil && o.StartScheduled.IsSet() {
		return true
	}

	return false
}

// SetStartScheduled gets a reference to the given NullableTime and assigns it to the StartScheduled field.
func (o *GetVideosVideoId200Response) SetStartScheduled(v time.Time) {
	o.StartScheduled.Set(&v)
}
// SetStartScheduledNil sets the value for StartScheduled to be an explicit nil
func (o *GetVideosVideoId200Response) SetStartScheduledNil() {
	o.StartScheduled.Set(nil)
}

// UnsetStartScheduled ensures that no value is present for StartScheduled, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetStartScheduled() {
	o.StartScheduled.Unset()
}

// GetStartActual returns the StartActual field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetStartActual() time.Time {
	if o == nil || o.StartActual.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartActual.Get()
}

// GetStartActualOk returns a tuple with the StartActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetStartActualOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartActual.Get(), o.StartActual.IsSet()
}

// HasStartActual returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasStartActual() bool {
	if o != nil && o.StartActual.IsSet() {
		return true
	}

	return false
}

// SetStartActual gets a reference to the given NullableTime and assigns it to the StartActual field.
func (o *GetVideosVideoId200Response) SetStartActual(v time.Time) {
	o.StartActual.Set(&v)
}
// SetStartActualNil sets the value for StartActual to be an explicit nil
func (o *GetVideosVideoId200Response) SetStartActualNil() {
	o.StartActual.Set(nil)
}

// UnsetStartActual ensures that no value is present for StartActual, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetStartActual() {
	o.StartActual.Unset()
}

// GetEndActual returns the EndActual field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetEndActual() time.Time {
	if o == nil || o.EndActual.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.EndActual.Get()
}

// GetEndActualOk returns a tuple with the EndActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetEndActualOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndActual.Get(), o.EndActual.IsSet()
}

// HasEndActual returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasEndActual() bool {
	if o != nil && o.EndActual.IsSet() {
		return true
	}

	return false
}

// SetEndActual gets a reference to the given NullableTime and assigns it to the EndActual field.
func (o *GetVideosVideoId200Response) SetEndActual(v time.Time) {
	o.EndActual.Set(&v)
}
// SetEndActualNil sets the value for EndActual to be an explicit nil
func (o *GetVideosVideoId200Response) SetEndActualNil() {
	o.EndActual.Set(nil)
}

// UnsetEndActual ensures that no value is present for EndActual, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetEndActual() {
	o.EndActual.Unset()
}

// GetLiveViewers returns the LiveViewers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetLiveViewers() int32 {
	if o == nil || o.LiveViewers.Get() == nil {
		var ret int32
		return ret
	}
	return *o.LiveViewers.Get()
}

// GetLiveViewersOk returns a tuple with the LiveViewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetLiveViewersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LiveViewers.Get(), o.LiveViewers.IsSet()
}

// HasLiveViewers returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasLiveViewers() bool {
	if o != nil && o.LiveViewers.IsSet() {
		return true
	}

	return false
}

// SetLiveViewers gets a reference to the given NullableInt32 and assigns it to the LiveViewers field.
func (o *GetVideosVideoId200Response) SetLiveViewers(v int32) {
	o.LiveViewers.Set(&v)
}
// SetLiveViewersNil sets the value for LiveViewers to be an explicit nil
func (o *GetVideosVideoId200Response) SetLiveViewersNil() {
	o.LiveViewers.Set(nil)
}

// UnsetLiveViewers ensures that no value is present for LiveViewers, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetLiveViewers() {
	o.LiveViewers.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetVideosVideoId200Response) SetDescription(v string) {
	o.Description = &v
}

// GetSongcount returns the Songcount field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetSongcount() float32 {
	if o == nil || o.Songcount == nil {
		var ret float32
		return ret
	}
	return *o.Songcount
}

// GetSongcountOk returns a tuple with the Songcount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetSongcountOk() (*float32, bool) {
	if o == nil || o.Songcount == nil {
		return nil, false
	}
	return o.Songcount, true
}

// HasSongcount returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasSongcount() bool {
	if o != nil && o.Songcount != nil {
		return true
	}

	return false
}

// SetSongcount gets a reference to the given float32 and assigns it to the Songcount field.
func (o *GetVideosVideoId200Response) SetSongcount(v float32) {
	o.Songcount = &v
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetChannelId() string {
	if o == nil || o.ChannelId == nil {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetChannelIdOk() (*string, bool) {
	if o == nil || o.ChannelId == nil {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasChannelId() bool {
	if o != nil && o.ChannelId != nil {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *GetVideosVideoId200Response) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetClips returns the Clips field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetClips() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Clips
}

// GetClipsOk returns a tuple with the Clips field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetClipsOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Clips == nil {
		return nil, false
	}
	return o.Clips, true
}

// HasClips returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasClips() bool {
	if o != nil && o.Clips != nil {
		return true
	}

	return false
}

// SetClips gets a reference to the given []VideoWithChannel and assigns it to the Clips field.
func (o *GetVideosVideoId200Response) SetClips(v []VideoWithChannel) {
	o.Clips = v
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetSources() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetSourcesOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []VideoWithChannel and assigns it to the Sources field.
func (o *GetVideosVideoId200Response) SetSources(v []VideoWithChannel) {
	o.Sources = v
}

// GetRefers returns the Refers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetRefers() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Refers
}

// GetRefersOk returns a tuple with the Refers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetRefersOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Refers == nil {
		return nil, false
	}
	return o.Refers, true
}

// HasRefers returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasRefers() bool {
	if o != nil && o.Refers != nil {
		return true
	}

	return false
}

// SetRefers gets a reference to the given []VideoWithChannel and assigns it to the Refers field.
func (o *GetVideosVideoId200Response) SetRefers(v []VideoWithChannel) {
	o.Refers = v
}

// GetSimulcasts returns the Simulcasts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetSimulcasts() []VideoWithChannel {
	if o == nil {
		var ret []VideoWithChannel
		return ret
	}
	return o.Simulcasts
}

// GetSimulcastsOk returns a tuple with the Simulcasts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetSimulcastsOk() ([]VideoWithChannel, bool) {
	if o == nil || o.Simulcasts == nil {
		return nil, false
	}
	return o.Simulcasts, true
}

// HasSimulcasts returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasSimulcasts() bool {
	if o != nil && o.Simulcasts != nil {
		return true
	}

	return false
}

// SetSimulcasts gets a reference to the given []VideoWithChannel and assigns it to the Simulcasts field.
func (o *GetVideosVideoId200Response) SetSimulcasts(v []VideoWithChannel) {
	o.Simulcasts = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetMentions() []ChannelMin {
	if o == nil {
		var ret []ChannelMin
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetMentionsOk() ([]ChannelMin, bool) {
	if o == nil || o.Mentions == nil {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasMentions() bool {
	if o != nil && o.Mentions != nil {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []ChannelMin and assigns it to the Mentions field.
func (o *GetVideosVideoId200Response) SetMentions(v []ChannelMin) {
	o.Mentions = v
}

// GetSongs returns the Songs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideosVideoId200Response) GetSongs() float32 {
	if o == nil || o.Songs.Get() == nil {
		var ret float32
		return ret
	}
	return *o.Songs.Get()
}

// GetSongsOk returns a tuple with the Songs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideosVideoId200Response) GetSongsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Songs.Get(), o.Songs.IsSet()
}

// HasSongs returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasSongs() bool {
	if o != nil && o.Songs.IsSet() {
		return true
	}

	return false
}

// SetSongs gets a reference to the given NullableFloat32 and assigns it to the Songs field.
func (o *GetVideosVideoId200Response) SetSongs(v float32) {
	o.Songs.Set(&v)
}
// SetSongsNil sets the value for Songs to be an explicit nil
func (o *GetVideosVideoId200Response) SetSongsNil() {
	o.Songs.Set(nil)
}

// UnsetSongs ensures that no value is present for Songs, not even an explicit nil
func (o *GetVideosVideoId200Response) UnsetSongs() {
	o.Songs.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetComments() []Comment {
	if o == nil || o.Comments == nil {
		var ret []Comment
		return ret
	}
	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetCommentsOk() ([]Comment, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given []Comment and assigns it to the Comments field.
func (o *GetVideosVideoId200Response) SetComments(v []Comment) {
	o.Comments = v
}

// GetRecommendations returns the Recommendations field value if set, zero value otherwise.
func (o *GetVideosVideoId200Response) GetRecommendations() []Video {
	if o == nil || o.Recommendations == nil {
		var ret []Video
		return ret
	}
	return o.Recommendations
}

// GetRecommendationsOk returns a tuple with the Recommendations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideosVideoId200Response) GetRecommendationsOk() ([]Video, bool) {
	if o == nil || o.Recommendations == nil {
		return nil, false
	}
	return o.Recommendations, true
}

// HasRecommendations returns a boolean if a field has been set.
func (o *GetVideosVideoId200Response) HasRecommendations() bool {
	if o != nil && o.Recommendations != nil {
		return true
	}

	return false
}

// SetRecommendations gets a reference to the given []Video and assigns it to the Recommendations field.
func (o *GetVideosVideoId200Response) SetRecommendations(v []Video) {
	o.Recommendations = v
}

func (o GetVideosVideoId200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.TopicId.IsSet() {
		toSerialize["topic_id"] = o.TopicId.Get()
	}
	if o.PublishedAt.IsSet() {
		toSerialize["published_at"] = o.PublishedAt.Get()
	}
	if o.AvailableAt != nil {
		toSerialize["available_at"] = o.AvailableAt
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StartScheduled.IsSet() {
		toSerialize["start_scheduled"] = o.StartScheduled.Get()
	}
	if o.StartActual.IsSet() {
		toSerialize["start_actual"] = o.StartActual.Get()
	}
	if o.EndActual.IsSet() {
		toSerialize["end_actual"] = o.EndActual.Get()
	}
	if o.LiveViewers.IsSet() {
		toSerialize["live_viewers"] = o.LiveViewers.Get()
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Songcount != nil {
		toSerialize["songcount"] = o.Songcount
	}
	if o.ChannelId != nil {
		toSerialize["channel_id"] = o.ChannelId
	}
	if o.Clips != nil {
		toSerialize["clips"] = o.Clips
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	if o.Refers != nil {
		toSerialize["refers"] = o.Refers
	}
	if o.Simulcasts != nil {
		toSerialize["simulcasts"] = o.Simulcasts
	}
	if o.Mentions != nil {
		toSerialize["mentions"] = o.Mentions
	}
	if o.Songs.IsSet() {
		toSerialize["songs"] = o.Songs.Get()
	}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	if o.Recommendations != nil {
		toSerialize["recommendations"] = o.Recommendations
	}
	return json.Marshal(toSerialize)
}

type NullableGetVideosVideoId200Response struct {
	value *GetVideosVideoId200Response
	isSet bool
}

func (v NullableGetVideosVideoId200Response) Get() *GetVideosVideoId200Response {
	return v.value
}

func (v *NullableGetVideosVideoId200Response) Set(val *GetVideosVideoId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideosVideoId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideosVideoId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideosVideoId200Response(val *GetVideosVideoId200Response) *NullableGetVideosVideoId200Response {
	return &NullableGetVideosVideoId200Response{value: val, isSet: true}
}

func (v NullableGetVideosVideoId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVideosVideoId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


