/*
Holodex/HoloAPI V2

Holodex Public API. Successor to the HoloAPI v1

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package holodex

import (
	"encoding/json"
)

// PostSearchVideoSearchRequestConditionsInner struct for PostSearchVideoSearchRequestConditionsInner
type PostSearchVideoSearchRequestConditionsInner struct {
	// Look for text in video title or description
	Text *string `json:"text,omitempty"`
}

// NewPostSearchVideoSearchRequestConditionsInner instantiates a new PostSearchVideoSearchRequestConditionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostSearchVideoSearchRequestConditionsInner() *PostSearchVideoSearchRequestConditionsInner {
	this := PostSearchVideoSearchRequestConditionsInner{}
	return &this
}

// NewPostSearchVideoSearchRequestConditionsInnerWithDefaults instantiates a new PostSearchVideoSearchRequestConditionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostSearchVideoSearchRequestConditionsInnerWithDefaults() *PostSearchVideoSearchRequestConditionsInner {
	this := PostSearchVideoSearchRequestConditionsInner{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *PostSearchVideoSearchRequestConditionsInner) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostSearchVideoSearchRequestConditionsInner) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *PostSearchVideoSearchRequestConditionsInner) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *PostSearchVideoSearchRequestConditionsInner) SetText(v string) {
	o.Text = &v
}

func (o PostSearchVideoSearchRequestConditionsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullablePostSearchVideoSearchRequestConditionsInner struct {
	value *PostSearchVideoSearchRequestConditionsInner
	isSet bool
}

func (v NullablePostSearchVideoSearchRequestConditionsInner) Get() *PostSearchVideoSearchRequestConditionsInner {
	return v.value
}

func (v *NullablePostSearchVideoSearchRequestConditionsInner) Set(val *PostSearchVideoSearchRequestConditionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostSearchVideoSearchRequestConditionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostSearchVideoSearchRequestConditionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostSearchVideoSearchRequestConditionsInner(val *PostSearchVideoSearchRequestConditionsInner) *NullablePostSearchVideoSearchRequestConditionsInner {
	return &NullablePostSearchVideoSearchRequestConditionsInner{value: val, isSet: true}
}

func (v NullablePostSearchVideoSearchRequestConditionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostSearchVideoSearchRequestConditionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


